# allow quay.io images
global:
  security:
    allowInsecureImages: true

keycloak:
  enabled: true
  image:
    registry: quay.io
    repository: keycloak/keycloak
    tag: "21.1.2"
    pullPolicy: IfNotPresent

postgresql:
  enabled: false

externalDatabase:
  host: si-postgres-postgresql
  port: 5432
  user: postgres
  password: postgres
  database: postgres

persistence:
  enabled: false

auth:
  adminUser:  admin
  adminPassword: admin

extraEnvVars:
  - name: KC_IMPORT
    value: "/tmp/realm.json"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"

extraVolumes:
  - name: realm-json
    configMap:
      name: keycloak-realm

extraVolumeMounts:
  - name: realm-json
    mountPath: /tmp/realm.json
    subPath: realm.json

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  tls:
    termination: edge