image:
  repository: ghcr.io/danwinga/si-backend
  tag: latest

secretName: si-backend-secret

replicaCount: 1

# Expose containerPort 8000 → service port 8000
service:
  port: 8000
  targetPort: 8000

# Enable Route on that same port
route:
  enabled: true
  host: ""   # leave blank to let OCP auto-generate <name>-<ns>.<cluster>