image:
  repository: ghcr.io/${REPO_OWNER}/si-backend
  tag: latest

secretName: si-backend-secret

replicaCount: 1
service:
  port: 80
  targetPort: 8000
route:
  enabled: true
  host: ""     # leave empty to let OpenShift choose <name>-<namespace>.<cluster>