# Default values for si-backend-api

# Number of API replicas
replicaCount: 1

# Container image
# image:
#   repository: ghcr.io/danwinga/si-backend
#   tag: latest
#   pullPolicy: IfNotPresent
image:
  repository: ghcr.io/danwinga/si-backend
  tag: latest
  pullPolicy: Always     # <— add this

# Service ports
service:
  port: 80          # the ClusterIP service port
  targetPort: 8000  # the container port your Django app listens on

# Route settings
route:
  enabled: true
  # host: ""        # optional override; if empty OpenShift will assign

# The Kubernetes Secret holding all your envFrom vars
secretName: si-backend-secret