
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    dns:
      - 8.8.8.8
      - 1.1.1.1

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    dns:
      - 8.8.8.8
      - 1.1.1.1

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    dns:
      - 8.8.8.8
      - 1.1.1.1

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - keycloak    
    restart: on-failure
    dns:
      - 8.8.8.8
      - 1.1.1.1
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    env_file: .env
    depends_on:
      - postgres
      - rabbitmq
      - keycloak
    restart: on-failure
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  pgdata:
  rabbitdata: