{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "si-notifications-worker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "si-notifications-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8080
{{- end }}