# Bitnami Keycloak overrides

image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: "21.1.2"
  pullPolicy: IfNotPresent

# We use our own Postgres, so disable the bundled one
postgresql:
  enabled: false

# Ephemeral, no PVC
persistence:
  enabled: false

# Admin console credentials (must be in your GitHub Secrets too)
auth:
  adminUser:  "${{ secrets.KC_ADMIN_USER | default "admin" }}"
  adminPassword: "${{ secrets.KC_ADMIN_PASSWORD | default "admin" }}"

# Import your realm JSON on startup
extraEnvVars:
  - name: KC_IMPORT
    value: "/tmp/realm.json"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"

# Mount the realm-export.json ConfigMap
extraVolumes:
  - name: realm-json
    configMap:
      name: keycloak-realm

extraVolumeMounts:
  - name: realm-json
    mountPath: /tmp/realm.json
    subPath: realm.json

# Expose only a ClusterIP service; we create an OpenShift Route
service:
  type: ClusterIP
  port: 8080

# No ingress (we use a Route)
ingress:
  enabled: false

route:
  enabled: true
  host: ""       # auto-generated by OpenShift
  tls:
    termination: edge