# helm/keycloak/values.yaml

keycloak:
  enabled: true

  # disable bundled Postgres
  postgresql:
    enabled: false

  # point at your external Postgres service
  externalDatabase:
    host:     si-postgres-postgresql
    port:     5432
    user:     postgres
    password: postgres
    database: postgres

  # make Keycloak ephemeral
  persistence:
    enabled: false

  # import your realm JSON
  extraEnvVars:
    - name: KEYCLOAK_IMPORT
      value: "/tmp/realm.json"
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"

  extraVolumes:
    - name: realm-json
      configMap:
        name: keycloak-realm

  extraVolumeMounts:
    - name: realm-json
      mountPath: /tmp/realm.json
      subPath: realm.json

  service:
    type: ClusterIP
    port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge