# Allow non-Bitnami images
global:
  security:
    allowInsecureImages: true

# Use Quay’s Keycloak image
image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: "21.1.2"
  pullPolicy: IfNotPresent

# Disable the built-in Postgres subchart
postgresql:
  enabled: false

# Use your external Postgres release “si-postgres”:
externalDatabase:
  host: si-postgres-postgresql
  port: 5432
  user: postgres
  database: postgres
  # The Bitnami Postgres chart creates a Secret named si-postgres-postgresql
  existingSecret: si-postgres-postgresql

# No persistence for demo
persistence:
  enabled: false

# Import your realm JSON on startup
extraEnvVars:
  - name: KC_IMPORT
    value: "/tmp/realm.json"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"

# Mount the realm ConfigMap
extraVolumes:
  - name: realm-json
    configMap:
      name: keycloak-realm

extraVolumeMounts:
  - name: realm-json
    mountPath: /tmp/realm.json
    subPath: realm.json

# Expose as ClusterIP; Route is handled separately
service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge