# Allow quay.io/keycloak/keycloak
global:
  security:
    allowInsecureImages: true

image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: "21.1.2"
  pullPolicy: IfNotPresent

# Disable the internal Postgres
postgresql:
  enabled: false

# Point to external Bitnami Postgres release 'si-postgres'
externalDatabase:
  host: si-postgres-postgresql
  port: 5432
  user: postgres
  database: postgres
  # The Bitnami Postgres chart creates 'si-postgres-postgresql' Secret with key 'postgresql-password'
  password:
    secret: si-postgres-postgresql
    key: postgresql-password

# No persistent volume needed for demo
persistence:
  enabled: false

# Import your realm JSON
extraEnvVars:
  - name: KC_IMPORT
    value: "/tmp/realm.json"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"

# Mount the realm JSON
extraVolumes:
  - name: realm-json
    configMap:
      name: keycloak-realm

extraVolumeMounts:
  - name: realm-json
    mountPath: /tmp/realm.json
    subPath: realm.json

# Expose as ClusterIP; Route enabled below
service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge