enabled: true

keycloak:
  enabled: true
  replicaCount: 1

  image:
    registry: quay.io
    repository: keycloak/keycloak
    tag: "21.1.2"
    pullPolicy: IfNotPresent

  # Use bundled Postgres
  postgresql:
    enabled: true

  persistence:
    enabled: false

  auth:
    adminUser: admin            # override via --set in CD
    adminPassword: admin        # override via --set in CD

  extraEnvVars:
    - name: KC_IMPORT
      value: /tmp/realm.json
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"

  extraVolumes:
    - name: realm-json
      configMap:
        name: keycloak-realm

  extraVolumeMounts:
    - name: realm-json
      mountPath: /tmp/realm.json
      subPath: realm.json

# OpenShift Route settings
route:
  enabled: true
  tls:
    termination: edge