# helm/keycloak/values.yaml

# Enable or disable this entire Keycloak umbrella chart
enabled: true

# Settings for the Bitnami 'keycloak' subchart
keycloak:
  enabled: true
  replicaCount: 1

  # Use the Quay Keycloak 21.1.2 image
  image:
    registry: quay.io
    repository: keycloak/keycloak
    tag: "21.1.2"
    pullPolicy: IfNotPresent

  # Use built-in H2 database for dev/test (no persistence)
  postgresql:
    enabled: false

  persistence:
    enabled: false

  # Admin console credentials
  auth:
    adminUser: admin
    adminPassword: admin

  # Environment variables to import your realm & enable health/metrics
  extraEnvVars:
    - name: KC_IMPORT
      value: /tmp/realm.json
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"

  # Mount the ConfigMap 'keycloak-realm' as /tmp/realm.json
  extraVolumes:
    - name: realm-json
      configMap:
        name: keycloak-realm

  extraVolumeMounts:
    - name: realm-json
      mountPath: /tmp/realm.json
      subPath: realm.json

  # Service settings (ClusterIP only; Route created separately)
  service:
    type: ClusterIP
    port: 8080

  # Do not create ingress/ingressRoute in this chart
  ingress:
    enabled: false

# Create an OpenShift Route
route:
  enabled: true
  # leave host blank to auto-generate <name>-<namespace>.<cluster>
  host: ""
  tls:
    termination: edge