# Allow non‐Bitnami (Quay) images
global:
  security:
    allowInsecureImages: true

# Which Keycloak image to use
image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: "21.1.2"
  pullPolicy: IfNotPresent

# Use external Postgres
externalDatabase:
  host: si-postgres-postgresql
  port: 5432
  user: postgres
  database: postgres
  existingSecret: si-postgres-postgresql

# No persistence for demo
persistence:
  enabled: false

# Import your realm JSON
extraEnvVars:
  - name: KC_IMPORT
    value: "/tmp/realm.json"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"

# Mount the ConfigMap with your realm-export.json
extraVolumes:
  - name: realm-json
    configMap:
      name: keycloak-realm

extraVolumeMounts:
  - name: realm-json
    mountPath: /tmp/realm.json
    subPath: realm.json

# Service only, Route is created via chart
service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge