keycloak:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/keycloak
    tag: "26.2.5-debian-12-r1"
    pullPolicy: IfNotPresent
  postgresql:
    enabled: false
  persistence:
    enabled: false
  auth:
    adminUser:  admin
    adminPassword: admin
  extraEnvVars:
    - name: KEYCLOAK_IMPORT
      value: "/tmp/realm.json"
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_METRICS_ENABLED
      value: "true"
  extraVolumes:
    - name: realm-json
      configMap:
        name: keycloak-realm
  extraVolumeMounts:
    - name: realm-json
      mountPath: /tmp/realm.json
      subPath: realm.json
  service:
    type: ClusterIP
    port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge