{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
{{- end }}