# -------------------------------------------------------------------
# 1) realm ConfigMap
# -------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: danwinga-dev
data:
  realm.json: |
    {
      "id": "si",
      "realm": "si",
      "enabled": true,
      "clients": [
        {
          "clientId": "si-backend",
          "secret": "supersecret",
          "publicClient": false,
          "directAccessGrantsEnabled": true,
          "redirectUris": ["*"]
        }
      ],
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "email": "dibomawhite@gmail.com",
          "credentials": [
            { "type": "password", "value": "password", "temporary": false }
          ]
        }
      ]
    }

---
# -------------------------------------------------------------------
# 2) Deployment
# -------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: si-keycloak
  namespace: danwinga-dev
  labels:
    app: si-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: si-keycloak
  template:
    metadata:
      labels:
        app: si-keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.1.2
          command:
            - /opt/keycloak/bin/kc.sh
          args:
            - start
            - --db=postgres
            - --import-realm
            - --http-port=8080
            - --http-relative-path=/auth
            - --hostname=si-keycloak-danwinga-dev.apps.rm3.7wse.p1.openshiftapps.com
            - --hostname-strict=false
            - --hostname-strict-https=true
          env:
            # Admin credentials
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            # JDBC settings
            - name: KC_DB_URL
              value: "jdbc:postgresql://si-postgres-postgresql:5432/keycloak"
            - name: KC_DB_USERNAME
              value: "postgres"
            - name: KC_DB_PASSWORD
              value: "postgres"
            # Skip Liquibase validation
            - name: QUARKUS_LIQUIBASE_VALIDATE_ON_MIGRATE
              value: "false"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-volume
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: realm-volume
          configMap:
            name: keycloak-realm

---
# -------------------------------------------------------------------
# 3) Service
# -------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: si-keycloak
  namespace: danwinga-dev
  labels:
    app: si-keycloak
spec:
  selector:
    app: si-keycloak
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

---
# -------------------------------------------------------------------
# 4) OpenShift Route (edge TLS)
# -------------------------------------------------------------------
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: si-keycloak
  namespace: danwinga-dev
spec:
  host: si-keycloak-danwinga-dev.apps.rm3.7wse.p1.openshiftapps.com
  to:
    kind: Service
    name: si-keycloak
  port:
    targetPort: http
  tls:
    termination: edge